const submissions=[{title:'Eclipsed Brand',student:'Mia Johnson',major:'Marketing',category:'Digital Art',likes:42,status:'Shortlisted',description:'A surreal visual narrative about brand identity, memory, and the emotional pull of immersive experiences.'},{title:'After the Spotlight',student:'Daniel Kim',major:'Integrated Marketing Communications',category:'Photography / Collage',likes:31,status:'Under Review',description:'A photo-collage exploring attention, transformation, and how audiences interpret a moment as an experience.'},{title:'When Time Makes Meaning',student:'Ariana Lopez',major:'Marketing',category:'Literary Expression',likes:18,status:'Submitted',description:'A short reflective piece connecting emotion, place, and the way experience shapes memory.'},{title:'Form in Motion',student:'Noah Patel',major:'Business',category:'Traditional Visual Art',likes:57,status:'Shortlisted',description:'An abstract mixed-media composition inspired by movement, rhythm, and the visual language of campaigns.'},{title:'The Quiet Campaign',student:'Sofia Reyes',major:'Marketing',category:'Digital Art',likes:24,status:'Submitted',description:'A minimalist digital piece on persuasion, silence, and the visual weight of intention.'},{title:'City in Red',student:'Ethan Brooks',major:'Marketing',category:'Photography / Collage',likes:29,status:'Under Review',description:'A layered composition using contrast, movement, and urban rhythm to frame brand storytelling.'}];
const gallery=document.getElementById('galleryGrid');
const search=document.getElementById('search');
const filter=document.getElementById('categoryFilter');
function render(items){gallery.innerHTML=items.map(item=>`<article class="gallery-item"><div class="head"><div><div class="tags"><span class="tag">${item.category}</span><span class="tag alt">${item.status}</span></div><h3>${item.title}</h3><p>${item.student} • ${item.major}</p></div><div class="badge">${item.likes} likes</div></div><p>${item.description}</p><div class="footer"><span>Preview · Notes</span><strong>Open ↗</strong></div></article>`).join('')}
function applyFilters(){const q=search.value.toLowerCase().trim();const cat=filter.value;const results=submissions.filter(item=>{const text=`${item.title} ${item.student} ${item.major} ${item.category} ${item.description}`.toLowerCase();return(!q||text.includes(q))&&(cat==='All'||item.category===cat)});render(results)}
search.addEventListener('input',applyFilters);
filter.addEventListener('change',applyFilters);
render(submissions);
